name: stress
on: workflow_dispatch
jobs:
  stress:
    runs-on: ubuntu-24.04-arm
    steps:
      - run: |
          openssl speed -evp chacha20-poly1305
  stress-2:
    runs-on: ubuntu-24.04
    steps:
      - run: |
          openssl speed -evp chacha20-poly1305
